### ISSUE TITLE
Running a black-box optimization

### ISSUE THREAD

**Issue by timmens** [simopt-admin/simopt#33]
Hello!

I've stumbled across the [ASTRO-DF paper](https://arxiv.org/abs/1610.06506) and found that your package implements this and other algorithms. I really want to try out the ASTRO-DF algorithm on my problems, but unfortunately, I did not manage to build a bridge between my code and your (``ProblemSolver``, ``Solver``, ``Problem``, ``Model``) architecture. It would be amazing if you could point me to the right demo file or documentation section, or help me use my code with your package! Let me show you a (minimal) example of how my problem specification looks:

```python
def criterion(x):
    # This could be any black-box function.
    # I always have a single parameter argument, which might be an array.
    return np.sum(x ** 2)
    
starting_values = np.arange(5)
lower_bounds = -1 * np.ones_like(starting_values)
```

Abstractly, given this specification, I want to run a local minimization like:

```python
optimization_result = minimize(
    criterion=criterion,
    starting_values=starting_values,
    lower_bounds=lower_bounds,
    upper_bounds=None,
    noisy=False
)
```

Three remarks:
1. For some problems I also have a gradient function available.
2. For some problems I have a non-linear constraint, defined as a function ``g`` that has to satisfy ``g(x) >= 0``.
3. With the ``noisy`` flag I mean that I have categorized my objective functions (problems) by whether they are deterministic or stochastic, but that's it. I don't know whether your solvers can already use this information.

Hopefully, you can help me with this problem. Thank you so much in advance!

**Comment by sean-reed** [comment]
You would subclass the Model class (from SimOpt.base) and pass the criterion function in the constructor and implement the replicate method to return its result (and gradient). You would then subclass the Problem class and pass in the criterion, lower bounds, and upper bounds to the constructor and instantiate your model. The starting values can be passed in a dictionary to the model_fixed_factors parameter of the Problem class constructor with the key "initial_solution". You need to also set the relevant attributes and implement certain methods in your model and problem classes, refer to the examples in the simopt.models folder, like cntnv.py.  Then you can run solvers, like ASTRO-DF, against your problem in the same way as any other. The library is intended for stochastic problems, so all the solvers assume your objective function is noisy.

**Comment by timmens** [comment]
Hello again!

Thank you for your detailed response!

I've followed your instructions, implemented a wrapper around the Model and Problem classes, and added that wrapper to the optimization library I'm working on. You can view the pull request [here](https://github.com/OpenSourceEconomics/estimagic/pull/393). Feedback from you or your team is very much welcome!

If you're curious, we invite you to check out our [documentation](https://estimagic.readthedocs.io/en/latest/algorithms.html#the-simopt-optimizers-simopt), where you'll also find a section on your optimizers.
