### ISSUE TITLE
Allow arbitrary number of arcs in SAN

### ISSUE THREAD

**Issue by Mark-L-Stone** [simopt-admin/simopt#5]
"Upgrade" request for SAN.
Rather than the number of arcs being fixed at 13, make the number of arcs an input parameter, with no limit on how large the number of arcs can be.  Provide this capability for both objective function and gradient.

**Comment by simopt-admin** [comment]
Thank you very much for your suggestion! On the RNDSAN branch, there is a problem (SANRND) which generates random stochastic activity networks. The number of nodes and arcs can be given as inputs. We are also developing this kind of generalized SAN problem on the python branch.

**Comment by Mark-L-Stone** [comment]
Sounds good. Except, where do I find the RNDSAN branch?

Maybe I'm also missing out on a bunch of other stuff I don't see?

**Comment by Mark-L-Stone** [comment]
I found the RNDSAN branch at https://github.com/simopt-admin/simopt/tree/RNDSAN/Problems/SAN . But i see there only code for 13 arcs and 9 nodes. Can you provide a link or detailed instructions on how to get the m file for which the number of nodes and arcs can be given as inputs?

Thanks.

**Comment by simopt-admin** [comment]
Here is a link to the SANRND problem on the RNDSAN branch: [https://github.com/simopt-admin/simopt/tree/RNDSAN/Problems/SANRND](https://github.com/simopt-admin/simopt/tree/RNDSAN/Problems/SANRND). See [SANRNDGenerate.m](https://github.com/simopt-admin/simopt/blob/RNDSAN/Problems/SANRND/SANRNDGenerate.m) in particular. The RunWrapper.m function in the Experiments folder on that branch is also modified to generate random problem instances.

In general, you should be able to switch between branches by clicking into a dropdown menu in the upper-left corner:
![branches](https://user-images.githubusercontent.com/52267122/91378679-a3833200-e7e6-11ea-988f-3393e0dc6dd1.PNG)
